defaults:
    - _self_
    - override hydra/job_logging: stdout

interval: 1h
max_parallel_count: 1

symbols:
  - AAPL

split:
  - name: train
    range: ???
    start: ???
    end: ???
  - name: test
    range: ???
    start: ???
    end: ???
  - name: val
    range: ???
    start: ???
    end: ???
