defaults:
    - _self_
    - override hydra/job_logging: stdout

interval: ??? # 1h for yf / 1Min for alpaca
worker_count: -1
skip_download: false

symbols:
  - AAPL
  - NVDA
  - GOOG
  - MSFT
  - AMZN
  - PYPL
  - TSLA
  - AMD
  - INTC

split:
  train: 0.8
  dev: 0.1
  test: 0.1

range: null
start: ???
end: ???
