defaults:
  - loss@pl_model.loss: focal
  - optimizer: adamw
  - lr_scheduler/step_based@pl_model.step_based: cosine_annealing
  - lr_scheduler/metric_based@pl_model.metric_based: reduce_on_plateau
  - model: fast_conformer
  - _self_
  - override hydra/job_logging: stdout

experiment:
  metric_to_track: val/f1score
  metric_mode: max
  seed: 7
  save_top_k: 50
  output_dir: ???
  grad_acc: ???

trainer:
  devices: -1
  accelerator: gpu
  strategy: ddp
  accumulate_grad_batches: ${experiment.grad_acc}
  default_root_dir: ${experiment.output_dir}
  num_sanity_val_steps: 1
  precision: bf16
  logger: true
  min_epochs: 60
  max_epochs: 100
  profiler: simple
  val_check_interval: 0.3 # probability out of 1.0. NOTE: will change into stepscount during runtime...
  limit_train_batches: null # NOTE: will be updated during runtime...

data:
  symbols:
    AAPL: null
    NVDA: null
    GOOG: null
    MSFT: null
    AMZN: null
    PYPL: null
    TSLA: null
    AMD: null
    INTC: null

  num_workers: 1
  batch_size: 8
  buffer_factor: 2
  src: yfinancesource
  interval: 1m

pl_model:
  metric_name: ${experiment.metric_to_track}
  grad_acc: ${experiment.grad_acc}
  scheduler_frequency: 1
  scheduler_interval: epoch
  metric_based:
    mode: ${experiment.metric_mode}

plt_callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${experiment.output_dir}/checkpoints
    filename: "{epoch}-{${experiment.metric_to_track}:.2f}"
    save_top_k: ${experiment.save_top_k}
    save_last: true
    verbose: true
    monitor: ${experiment.metric_to_track}
    mode: ${experiment.metric_mode}
    every_n_train_steps: ${trainer.val_check_interval}
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  - _target_: pytorch_lightning.callbacks.ModelSummary
    max_depth: 2
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: ${experiment.metric_to_track}
    patience: ${experiment.patience}
    verbose: true
    mode: ${experiment.metric_mode}

hydra:
  run:
    dir: ${experiment.output_dir}
