defaults:
  - loss@pl_model.loss: focal
  - optimizer: adamw
  - lr_scheduler/step_based@pl_model.step_based: cosine_annealing
  - lr_scheduler/metric_based@pl_model.metric_based: reduce_on_plateau
  - model: conf_encoder_with_heads
  - pl_trainer_callbacks
  - _self_
  - override hydra/job_logging: stdout

symbols_info:
  AAPL:
    train: true
    dev: true
    test: true
  NVDA:
    train: true
    dev: true
    test: true
  # ...

experiment:
  metric_to_track: val/loss
  metric_mode: min
  output_dir: ???
  grad_acc: ???

  seed: 7
  save_top_k: 5

trainer:
  devices: -1
  accelerator: gpu
  strategy: ddp
  accumulate_grad_batches: ${experiment.grad_acc}
  default_root_dir: ${experiment.output_dir}
  num_sanity_val_steps: 1
  precision: 32
  logger: true
  min_epochs: 40
  max_epochs: 100
  profiler: simple
  val_check_interval: 0.3 # probability out of 1.0. NOTE: will change into stepscount during runtime...
  limit_train_batches: null # NOTE: will be updated during runtime...

data:
  symbols: ${symbols_info}
  num_workers: 16
  batch_size: 32
  buffer_factor: 4

pl_model:
  metric: ${experiment.metric_to_track}
  scheduler_frequency: 1
  scheduler_interval: epoch
  metric_based:
    mode: ${experiment.metric_mode}

hydra:
  run:
    dir: ${experiment.output_dir}
